/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'id' : bigint,
  'contentFa' : string,
  'contentSv' : string,
  'imagePath' : [] | [string],
}
export interface Activity {
  'id' : bigint,
  'contentFa' : string,
  'contentSv' : string,
  'topic' : Topic,
  'descriptionFa' : string,
  'descriptionSv' : string,
  'createdAt' : bigint,
  'slug' : string,
  'isActive' : boolean,
  'updatedAt' : bigint,
  'imageUrl' : [] | [Blob],
  'hasRegistrationForm' : boolean,
  'titleFa' : string,
  'titleSv' : string,
}
export interface Area {
  'id' : bigint,
  'order' : bigint,
  'icon' : string,
  'cardBackground' : [] | [Blob],
  'subtitleFa' : string,
  'subtitleSv' : string,
  'areaBackgroundVideo' : [] | [Blob],
  'areaBackground' : [] | [Blob],
  'titleFa' : string,
  'titleSv' : string,
}
export interface AreaInput {
  'icon' : string,
  'subtitleFa' : string,
  'subtitleSv' : string,
  'titleFa' : string,
  'titleSv' : string,
}
export interface Background {
  'id' : bigint,
  'activitySlug' : [] | [string],
  'scope' : BackgroundScope,
  'imageUrl' : [] | [Blob],
  'mediaType' : [] | [string],
}
export type BackgroundScope = { 'Sport' : null } |
  { 'Cultural' : null } |
  { 'Educational' : null } |
  { 'Landing' : null } |
  { 'Activity' : null };
export interface ContactInfo {
  'id' : bigint,
  'email' : string,
  'addressFa' : string,
  'addressSv' : string,
  'mapEmbedUrl' : [] | [string],
  'phone' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : [] | [string],
}
export interface ContactSubmissionInput {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : [] | [string],
}
export type Blob = Uint8Array;
export interface FooterLink {
  'id' : bigint,
  'url' : string,
  'labelFa' : string,
  'labelSv' : string,
  'order' : bigint,
  'category' : string,
}
export interface HeroSlide {
  'id' : bigint,
  'topic' : Topic,
  'order' : bigint,
  'isActive' : boolean,
  'imageUrl' : [] | [Blob],
  'subtitleFa' : string,
  'subtitleSv' : string,
  'titleFa' : string,
  'titleSv' : string,
}
export interface RegistrationInput {
  'nameFa' : [] | [string],
  'nameSv' : [] | [string],
  'activityId' : bigint,
  'email' : string,
  'message' : [] | [string],
  'phone' : [] | [string],
}
export interface RegistrationSubmission {
  'id' : bigint,
  'status' : SubmissionStatus,
  'nameFa' : [] | [string],
  'nameSv' : [] | [string],
  'activityId' : bigint,
  'submittedAt' : bigint,
  'email' : string,
  'message' : [] | [string],
  'phone' : [] | [string],
}
export interface SiteSettings {
  'id' : bigint,
  'landingSubtitleFa' : string,
  'landingSubtitleSv' : string,
  'primaryColor' : string,
  'topicsBgVideo' : [] | [Blob],
  'accentColor' : string,
  'logoUrl' : [] | [Blob],
  'adminPassword' : string,
  'secondaryColor' : string,
  'topicsBgImage' : [] | [Blob],
  'titleFa' : string,
  'titleSv' : string,
}
export type SubmissionStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type Topic = { 'Sport' : null } |
  { 'Cultural' : null } |
  { 'Educational' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addActivity' : ActorMethod<
    [string, Activity],
    { 'ok' : Activity } |
      { 'err' : string }
  >,
  'addArea' : ActorMethod<
    [string, AreaInput],
    { 'ok' : Area } |
      { 'err' : string }
  >,
  'addFooterLink' : ActorMethod<
    [string, FooterLink],
    { 'ok' : FooterLink } |
      { 'err' : string }
  >,
  'addHeroSlide' : ActorMethod<
    [string, HeroSlide],
    { 'ok' : HeroSlide } |
      { 'err' : string }
  >,
  'adminLogin' : ActorMethod<[string], [] | [string]>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteActivity' : ActorMethod<
    [string, bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteArea' : ActorMethod<
    [string, bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteContactSubmission' : ActorMethod<
    [string, bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteFooterLink' : ActorMethod<
    [string, bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteHeroSlide' : ActorMethod<
    [string, bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteSubmission' : ActorMethod<
    [string, bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'emergencyResetPassword' : ActorMethod<[string], boolean>,
  'getAbout' : ActorMethod<[], AboutContent>,
  'getActivities' : ActorMethod<[[] | [Topic]], Array<Activity>>,
  'getActivityBySlug' : ActorMethod<[string], [] | [Activity]>,
  'getAllActivitiesAdmin' : ActorMethod<[[] | [Topic]], Array<Activity>>,
  'getAllHeroSlides' : ActorMethod<[], Array<HeroSlide>>,
  'getAreas' : ActorMethod<[], Array<Area>>,
  'getBackgrounds' : ActorMethod<[], Array<Background>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getContactSubmissions' : ActorMethod<
    [string],
    { 'ok' : Array<ContactSubmission> } |
      { 'err' : string }
  >,
  'getFooterLinks' : ActorMethod<[], Array<FooterLink>>,
  'getHeroSlides' : ActorMethod<[Topic], Array<HeroSlide>>,
  'getRegistrationSubmissions' : ActorMethod<
    [[] | [bigint]],
    Array<RegistrationSubmission>
  >,
  'getSiteSettings' : ActorMethod<[], [] | [SiteSettings]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderAreas' : ActorMethod<
    [string, Array<bigint>],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'reorderFooterLinks' : ActorMethod<
    [string, Array<bigint>],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'reorderHeroSlides' : ActorMethod<
    [string, Array<bigint>],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'resetAdminPassword' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'seedSampleData' : ActorMethod<[], boolean>,
  'setAbout' : ActorMethod<[string, AboutContent], boolean>,
  'setAreaBackground' : ActorMethod<
    [string, bigint, Blob],
    { 'ok' : [] | [Area] } |
      { 'err' : string }
  >,
  'setAreaBackgroundVideo' : ActorMethod<
    [string, bigint, Blob],
    { 'ok' : [] | [Area] } |
      { 'err' : string }
  >,
  'setAreaCardBackground' : ActorMethod<
    [string, bigint, Blob],
    { 'ok' : [] | [Area] } |
      { 'err' : string }
  >,
  'setBackground' : ActorMethod<
    [string, Background],
    { 'ok' : Background } |
      { 'err' : string }
  >,
  'setContactInfo' : ActorMethod<
    [string, ContactInfo],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'setSiteSettings' : ActorMethod<
    [string, SiteSettings],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'submitContactForm' : ActorMethod<
    [ContactSubmissionInput],
    ContactSubmission
  >,
  'submitRegistration' : ActorMethod<
    [RegistrationInput],
    RegistrationSubmission
  >,
  'updateActivity' : ActorMethod<
    [string, Activity],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateAdminPassword' : ActorMethod<
    [string, string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateArea' : ActorMethod<
    [string, bigint, AreaInput],
    { 'ok' : [] | [Area] } |
      { 'err' : string }
  >,
  'updateFooterLink' : ActorMethod<
    [string, FooterLink],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateHeroSlide' : ActorMethod<
    [string, HeroSlide],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateSubmissionStatus' : ActorMethod<
    [string, bigint, SubmissionStatus],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];