/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Topic = IDL.Variant({
  'Sport' : IDL.Null,
  'Cultural' : IDL.Null,
  'Educational' : IDL.Null,
});
export const Blob = IDL.Vec(IDL.Nat8);
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'contentFa' : IDL.Text,
  'contentSv' : IDL.Text,
  'topic' : Topic,
  'descriptionFa' : IDL.Text,
  'descriptionSv' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'imageUrl' : IDL.Opt(Blob),
  'hasRegistrationForm' : IDL.Bool,
  'titleFa' : IDL.Text,
  'titleSv' : IDL.Text,
});
export const AreaInput = IDL.Record({
  'icon' : IDL.Text,
  'subtitleFa' : IDL.Text,
  'subtitleSv' : IDL.Text,
  'titleFa' : IDL.Text,
  'titleSv' : IDL.Text,
});
export const Area = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'cardBackground' : IDL.Opt(Blob),
  'subtitleFa' : IDL.Text,
  'subtitleSv' : IDL.Text,
  'areaBackgroundVideo' : IDL.Opt(Blob),
  'areaBackground' : IDL.Opt(Blob),
  'titleFa' : IDL.Text,
  'titleSv' : IDL.Text,
});
export const FooterLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'labelFa' : IDL.Text,
  'labelSv' : IDL.Text,
  'order' : IDL.Nat,
  'category' : IDL.Text,
});
export const HeroSlide = IDL.Record({
  'id' : IDL.Nat,
  'topic' : Topic,
  'order' : IDL.Nat,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Opt(Blob),
  'subtitleFa' : IDL.Text,
  'subtitleSv' : IDL.Text,
  'titleFa' : IDL.Text,
  'titleSv' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AboutContent = IDL.Record({
  'id' : IDL.Nat,
  'contentFa' : IDL.Text,
  'contentSv' : IDL.Text,
  'imagePath' : IDL.Opt(IDL.Text),
});
export const BackgroundScope = IDL.Variant({
  'Sport' : IDL.Null,
  'Cultural' : IDL.Null,
  'Educational' : IDL.Null,
  'Landing' : IDL.Null,
  'Activity' : IDL.Null,
});
export const Background = IDL.Record({
  'id' : IDL.Nat,
  'activitySlug' : IDL.Opt(IDL.Text),
  'scope' : BackgroundScope,
  'imageUrl' : IDL.Opt(Blob),
  'mediaType' : IDL.Opt(IDL.Text),
});
export const ContactInfo = IDL.Record({
  'id' : IDL.Nat,
  'email' : IDL.Text,
  'addressFa' : IDL.Text,
  'addressSv' : IDL.Text,
  'mapEmbedUrl' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Opt(IDL.Text),
});
export const SubmissionStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const RegistrationSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : SubmissionStatus,
  'nameFa' : IDL.Opt(IDL.Text),
  'nameSv' : IDL.Opt(IDL.Text),
  'activityId' : IDL.Nat,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const SiteSettings = IDL.Record({
  'id' : IDL.Nat,
  'landingSubtitleFa' : IDL.Text,
  'landingSubtitleSv' : IDL.Text,
  'primaryColor' : IDL.Text,
  'topicsBgVideo' : IDL.Opt(Blob),
  'accentColor' : IDL.Text,
  'logoUrl' : IDL.Opt(Blob),
  'adminPassword' : IDL.Text,
  'secondaryColor' : IDL.Text,
  'topicsBgImage' : IDL.Opt(Blob),
  'titleFa' : IDL.Text,
  'titleSv' : IDL.Text,
});
export const ContactSubmissionInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const RegistrationInput = IDL.Record({
  'nameFa' : IDL.Opt(IDL.Text),
  'nameSv' : IDL.Opt(IDL.Text),
  'activityId' : IDL.Nat,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addActivity' : IDL.Func(
      [IDL.Text, Activity],
      [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
      [],
    ),
  'addArea' : IDL.Func(
      [IDL.Text, AreaInput],
      [IDL.Variant({ 'ok' : Area, 'err' : IDL.Text })],
      [],
    ),
  'addFooterLink' : IDL.Func(
      [IDL.Text, FooterLink],
      [IDL.Variant({ 'ok' : FooterLink, 'err' : IDL.Text })],
      [],
    ),
  'addHeroSlide' : IDL.Func(
      [IDL.Text, HeroSlide],
      [IDL.Variant({ 'ok' : HeroSlide, 'err' : IDL.Text })],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteActivity' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteArea' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteFooterLink' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteHeroSlide' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteSubmission' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'emergencyResetPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAbout' : IDL.Func([], [AboutContent], ['query']),
  'getActivities' : IDL.Func([IDL.Opt(Topic)], [IDL.Vec(Activity)], ['query']),
  'getActivityBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Activity)], ['query']),
  'getAllActivitiesAdmin' : IDL.Func(
      [IDL.Opt(Topic)],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getAllHeroSlides' : IDL.Func([], [IDL.Vec(HeroSlide)], ['query']),
  'getAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
  'getBackgrounds' : IDL.Func([], [IDL.Vec(Background)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(ContactSubmission), 'err' : IDL.Text })],
      [],
    ),
  'getFooterLinks' : IDL.Func([], [IDL.Vec(FooterLink)], ['query']),
  'getHeroSlides' : IDL.Func([Topic], [IDL.Vec(HeroSlide)], ['query']),
  'getRegistrationSubmissions' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(RegistrationSubmission)],
      ['query'],
    ),
  'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderAreas' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'reorderFooterLinks' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'reorderHeroSlides' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'resetAdminPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'seedSampleData' : IDL.Func([], [IDL.Bool], []),
  'setAbout' : IDL.Func([IDL.Text, AboutContent], [IDL.Bool], []),
  'setAreaBackground' : IDL.Func(
      [IDL.Text, IDL.Nat, Blob],
      [IDL.Variant({ 'ok' : IDL.Opt(Area), 'err' : IDL.Text })],
      [],
    ),
  'setAreaBackgroundVideo' : IDL.Func(
      [IDL.Text, IDL.Nat, Blob],
      [IDL.Variant({ 'ok' : IDL.Opt(Area), 'err' : IDL.Text })],
      [],
    ),
  'setAreaCardBackground' : IDL.Func(
      [IDL.Text, IDL.Nat, Blob],
      [IDL.Variant({ 'ok' : IDL.Opt(Area), 'err' : IDL.Text })],
      [],
    ),
  'setBackground' : IDL.Func(
      [IDL.Text, Background],
      [IDL.Variant({ 'ok' : Background, 'err' : IDL.Text })],
      [],
    ),
  'setContactInfo' : IDL.Func(
      [IDL.Text, ContactInfo],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'setSiteSettings' : IDL.Func(
      [IDL.Text, SiteSettings],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [ContactSubmissionInput],
      [ContactSubmission],
      [],
    ),
  'submitRegistration' : IDL.Func(
      [RegistrationInput],
      [RegistrationSubmission],
      [],
    ),
  'updateActivity' : IDL.Func(
      [IDL.Text, Activity],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateAdminPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateArea' : IDL.Func(
      [IDL.Text, IDL.Nat, AreaInput],
      [IDL.Variant({ 'ok' : IDL.Opt(Area), 'err' : IDL.Text })],
      [],
    ),
  'updateFooterLink' : IDL.Func(
      [IDL.Text, FooterLink],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateHeroSlide' : IDL.Func(
      [IDL.Text, HeroSlide],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateSubmissionStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, SubmissionStatus],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Topic = IDL.Variant({
    'Sport' : IDL.Null,
    'Cultural' : IDL.Null,
    'Educational' : IDL.Null,
  });
  const Blob = IDL.Vec(IDL.Nat8);
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'contentFa' : IDL.Text,
    'contentSv' : IDL.Text,
    'topic' : Topic,
    'descriptionFa' : IDL.Text,
    'descriptionSv' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'imageUrl' : IDL.Opt(Blob),
    'hasRegistrationForm' : IDL.Bool,
    'titleFa' : IDL.Text,
    'titleSv' : IDL.Text,
  });
  const AreaInput = IDL.Record({
    'icon' : IDL.Text,
    'subtitleFa' : IDL.Text,
    'subtitleSv' : IDL.Text,
    'titleFa' : IDL.Text,
    'titleSv' : IDL.Text,
  });
  const Area = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'cardBackground' : IDL.Opt(Blob),
    'subtitleFa' : IDL.Text,
    'subtitleSv' : IDL.Text,
    'areaBackgroundVideo' : IDL.Opt(Blob),
    'areaBackground' : IDL.Opt(Blob),
    'titleFa' : IDL.Text,
    'titleSv' : IDL.Text,
  });
  const FooterLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'labelFa' : IDL.Text,
    'labelSv' : IDL.Text,
    'order' : IDL.Nat,
    'category' : IDL.Text,
  });
  const HeroSlide = IDL.Record({
    'id' : IDL.Nat,
    'topic' : Topic,
    'order' : IDL.Nat,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Opt(Blob),
    'subtitleFa' : IDL.Text,
    'subtitleSv' : IDL.Text,
    'titleFa' : IDL.Text,
    'titleSv' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AboutContent = IDL.Record({
    'id' : IDL.Nat,
    'contentFa' : IDL.Text,
    'contentSv' : IDL.Text,
    'imagePath' : IDL.Opt(IDL.Text),
  });
  const BackgroundScope = IDL.Variant({
    'Sport' : IDL.Null,
    'Cultural' : IDL.Null,
    'Educational' : IDL.Null,
    'Landing' : IDL.Null,
    'Activity' : IDL.Null,
  });
  const Background = IDL.Record({
    'id' : IDL.Nat,
    'activitySlug' : IDL.Opt(IDL.Text),
    'scope' : BackgroundScope,
    'imageUrl' : IDL.Opt(Blob),
    'mediaType' : IDL.Opt(IDL.Text),
  });
  const ContactInfo = IDL.Record({
    'id' : IDL.Nat,
    'email' : IDL.Text,
    'addressFa' : IDL.Text,
    'addressSv' : IDL.Text,
    'mapEmbedUrl' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Opt(IDL.Text),
  });
  const SubmissionStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const RegistrationSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : SubmissionStatus,
    'nameFa' : IDL.Opt(IDL.Text),
    'nameSv' : IDL.Opt(IDL.Text),
    'activityId' : IDL.Nat,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const SiteSettings = IDL.Record({
    'id' : IDL.Nat,
    'landingSubtitleFa' : IDL.Text,
    'landingSubtitleSv' : IDL.Text,
    'primaryColor' : IDL.Text,
    'topicsBgVideo' : IDL.Opt(Blob),
    'accentColor' : IDL.Text,
    'logoUrl' : IDL.Opt(Blob),
    'adminPassword' : IDL.Text,
    'secondaryColor' : IDL.Text,
    'topicsBgImage' : IDL.Opt(Blob),
    'titleFa' : IDL.Text,
    'titleSv' : IDL.Text,
  });
  const ContactSubmissionInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const RegistrationInput = IDL.Record({
    'nameFa' : IDL.Opt(IDL.Text),
    'nameSv' : IDL.Opt(IDL.Text),
    'activityId' : IDL.Nat,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addActivity' : IDL.Func(
        [IDL.Text, Activity],
        [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
        [],
      ),
    'addArea' : IDL.Func(
        [IDL.Text, AreaInput],
        [IDL.Variant({ 'ok' : Area, 'err' : IDL.Text })],
        [],
      ),
    'addFooterLink' : IDL.Func(
        [IDL.Text, FooterLink],
        [IDL.Variant({ 'ok' : FooterLink, 'err' : IDL.Text })],
        [],
      ),
    'addHeroSlide' : IDL.Func(
        [IDL.Text, HeroSlide],
        [IDL.Variant({ 'ok' : HeroSlide, 'err' : IDL.Text })],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteActivity' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteArea' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteFooterLink' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteHeroSlide' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteSubmission' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'emergencyResetPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAbout' : IDL.Func([], [AboutContent], ['query']),
    'getActivities' : IDL.Func(
        [IDL.Opt(Topic)],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getActivityBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Activity)], ['query']),
    'getAdminPasswordHash' : IDL.Func([], [IDL.Text], ['query']),
    'getAllActivitiesAdmin' : IDL.Func(
        [IDL.Opt(Topic)],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getAllHeroSlides' : IDL.Func([], [IDL.Vec(HeroSlide)], ['query']),
    'getAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
    'getBackgrounds' : IDL.Func([], [IDL.Vec(Background)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(ContactSubmission), 'err' : IDL.Text })],
        [],
      ),
    'getFooterLinks' : IDL.Func([], [IDL.Vec(FooterLink)], ['query']),
    'getHeroSlides' : IDL.Func([Topic], [IDL.Vec(HeroSlide)], ['query']),
    'getRegistrationSubmissions' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(RegistrationSubmission)],
        ['query'],
      ),
    'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderAreas' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'reorderFooterLinks' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'reorderHeroSlides' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'resetAdminPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'seedSampleData' : IDL.Func([], [IDL.Bool], []),
    'setAbout' : IDL.Func([IDL.Text, AboutContent], [IDL.Bool], []),
    'setAreaBackground' : IDL.Func(
        [IDL.Text, IDL.Nat, Blob],
        [IDL.Variant({ 'ok' : IDL.Opt(Area), 'err' : IDL.Text })],
        [],
      ),
    'setAreaBackgroundVideo' : IDL.Func(
        [IDL.Text, IDL.Nat, Blob],
        [IDL.Variant({ 'ok' : IDL.Opt(Area), 'err' : IDL.Text })],
        [],
      ),
    'setAreaCardBackground' : IDL.Func(
        [IDL.Text, IDL.Nat, Blob],
        [IDL.Variant({ 'ok' : IDL.Opt(Area), 'err' : IDL.Text })],
        [],
      ),
    'setBackground' : IDL.Func(
        [IDL.Text, Background],
        [IDL.Variant({ 'ok' : Background, 'err' : IDL.Text })],
        [],
      ),
    'setContactInfo' : IDL.Func(
        [IDL.Text, ContactInfo],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'setSiteSettings' : IDL.Func(
        [IDL.Text, SiteSettings],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [ContactSubmissionInput],
        [ContactSubmission],
        [],
      ),
    'submitRegistration' : IDL.Func(
        [RegistrationInput],
        [RegistrationSubmission],
        [],
      ),
    'updateActivity' : IDL.Func(
        [IDL.Text, Activity],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateAdminPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateArea' : IDL.Func(
        [IDL.Text, IDL.Nat, AreaInput],
        [IDL.Variant({ 'ok' : IDL.Opt(Area), 'err' : IDL.Text })],
        [],
      ),
    'updateFooterLink' : IDL.Func(
        [IDL.Text, FooterLink],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateHeroSlide' : IDL.Func(
        [IDL.Text, HeroSlide],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateSubmissionStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, SubmissionStatus],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };