/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AboutContent {
    id: bigint;
    contentFa: string;
    contentSv: string;
    imagePath?: string;
}
export interface ContactSubmission {
    id: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone?: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Background {
    id: bigint;
    activitySlug?: string;
    scope: BackgroundScope;
    imageUrl?: ExternalBlob;
    mediaType?: string;
}
export interface HeroSlide {
    id: bigint;
    topic: Topic;
    order: bigint;
    isActive: boolean;
    imageUrl?: ExternalBlob;
    subtitleFa: string;
    subtitleSv: string;
    titleFa: string;
    titleSv: string;
}
export interface AreaInput {
    icon: string;
    subtitleFa: string;
    subtitleSv: string;
    titleFa: string;
    titleSv: string;
}
export interface FooterLink {
    id: bigint;
    url: string;
    labelFa: string;
    labelSv: string;
    order: bigint;
    category: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface RegistrationInput {
    nameFa?: string;
    nameSv?: string;
    activityId: bigint;
    email: string;
    message?: string;
    phone?: string;
}
export interface SiteSettings {
    id: bigint;
    landingSubtitleFa: string;
    landingSubtitleSv: string;
    primaryColor: string;
    topicsBgVideo?: ExternalBlob;
    accentColor: string;
    logoUrl?: ExternalBlob;
    adminPassword: string;
    secondaryColor: string;
    topicsBgImage?: ExternalBlob;
    titleFa: string;
    titleSv: string;
}
export interface Activity {
    id: bigint;
    contentFa: string;
    contentSv: string;
    topic: Topic;
    descriptionFa: string;
    descriptionSv: string;
    createdAt: bigint;
    slug: string;
    isActive: boolean;
    updatedAt: bigint;
    imageUrl?: ExternalBlob;
    hasRegistrationForm: boolean;
    titleFa: string;
    titleSv: string;
}
export interface Area {
    id: bigint;
    order: bigint;
    icon: string;
    cardBackground?: ExternalBlob;
    subtitleFa: string;
    subtitleSv: string;
    areaBackgroundVideo?: ExternalBlob;
    areaBackground?: ExternalBlob;
    titleFa: string;
    titleSv: string;
}
export interface ContactSubmissionInput {
    name: string;
    email: string;
    message: string;
    phone?: string;
}
export interface RegistrationSubmission {
    id: bigint;
    status: SubmissionStatus;
    nameFa?: string;
    nameSv?: string;
    activityId: bigint;
    submittedAt: bigint;
    email: string;
    message?: string;
    phone?: string;
}
export interface ContactInfo {
    id: bigint;
    email: string;
    addressFa: string;
    addressSv: string;
    mapEmbedUrl?: string;
    phone: string;
}
export enum BackgroundScope {
    Sport = "Sport",
    Cultural = "Cultural",
    Educational = "Educational",
    Landing = "Landing",
    Activity = "Activity"
}
export enum SubmissionStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export enum Topic {
    Sport = "Sport",
    Cultural = "Cultural",
    Educational = "Educational"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addActivity(token: string, input: Activity): Promise<{
        __kind__: "ok";
        ok: Activity;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addArea(token: string, input: AreaInput): Promise<{
        __kind__: "ok";
        ok: Area;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addFooterLink(token: string, input: FooterLink): Promise<{
        __kind__: "ok";
        ok: FooterLink;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addHeroSlide(token: string, input: HeroSlide): Promise<{
        __kind__: "ok";
        ok: HeroSlide;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminLogin(password: string): Promise<string | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteActivity(token: string, id: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteArea(token: string, id: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteContactSubmission(token: string, id: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteFooterLink(token: string, id: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteHeroSlide(token: string, id: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteSubmission(token: string, id: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    emergencyResetPassword(recoverySecret: string): Promise<boolean>;
    getAbout(): Promise<AboutContent>;
    getActivities(topic: Topic | null): Promise<Array<Activity>>;
    getActivityBySlug(slug: string): Promise<Activity | null>;
    getAllActivitiesAdmin(topic: Topic | null): Promise<Array<Activity>>;
    getAllHeroSlides(): Promise<Array<HeroSlide>>;
    getAreas(): Promise<Array<Area>>;
    getBackgrounds(): Promise<Array<Background>>;
    getContactInfo(): Promise<ContactInfo | null>;
    getContactSubmissions(token: string): Promise<{
        __kind__: "ok";
        ok: Array<ContactSubmission>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getFooterLinks(): Promise<Array<FooterLink>>;
    getHeroSlides(topic: Topic): Promise<Array<HeroSlide>>;
    getRegistrationSubmissions(activityId: bigint | null): Promise<Array<RegistrationSubmission>>;
    getSiteSettings(): Promise<SiteSettings | null>;
    isCallerAdmin(): Promise<boolean>;
    reorderAreas(token: string, ids: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    reorderFooterLinks(token: string, orderedIds: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    reorderHeroSlides(token: string, orderedIds: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetAdminPassword(token: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    seedSampleData(): Promise<boolean>;
    setAbout(token: string, input: AboutContent): Promise<boolean>;
    setAreaBackground(token: string, areaId: bigint, blob: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: Area | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAreaBackgroundVideo(token: string, areaId: bigint, blob: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: Area | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAreaCardBackground(token: string, areaId: bigint, blob: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: Area | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setBackground(token: string, input: Background): Promise<{
        __kind__: "ok";
        ok: Background;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setContactInfo(token: string, input: ContactInfo): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setSiteSettings(token: string, input: SiteSettings): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitContactForm(input: ContactSubmissionInput): Promise<ContactSubmission>;
    submitRegistration(input: RegistrationInput): Promise<RegistrationSubmission>;
    updateActivity(token: string, updated: Activity): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateAdminPassword(token: string, currentPassword: string, newPassword: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateArea(token: string, id: bigint, input: AreaInput): Promise<{
        __kind__: "ok";
        ok: Area | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateFooterLink(token: string, updated: FooterLink): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateHeroSlide(token: string, updated: HeroSlide): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateSubmissionStatus(token: string, id: bigint, status: SubmissionStatus): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AboutContent as _AboutContent, Activity as _Activity, Area as _Area, Background as _Background, BackgroundScope as _BackgroundScope, ContactInfo as _ContactInfo, ContactSubmission as _ContactSubmission, ContactSubmissionInput as _ContactSubmissionInput, ExternalBlob as _ExternalBlob, FooterLink as _FooterLink, HeroSlide as _HeroSlide, RegistrationInput as _RegistrationInput, RegistrationSubmission as _RegistrationSubmission, SiteSettings as _SiteSettings, SubmissionStatus as _SubmissionStatus, Topic as _Topic, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addActivity(arg0: string, arg1: Activity): Promise<{
        __kind__: "ok";
        ok: Activity;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0, await to_candid_Activity_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0, await to_candid_Activity_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async addArea(arg0: string, arg1: AreaInput): Promise<{
        __kind__: "ok";
        ok: Area;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addArea(arg0, arg1);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArea(arg0, arg1);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFooterLink(arg0: string, arg1: FooterLink): Promise<{
        __kind__: "ok";
        ok: FooterLink;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addFooterLink(arg0, arg1);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFooterLink(arg0, arg1);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async addHeroSlide(arg0: string, arg1: HeroSlide): Promise<{
        __kind__: "ok";
        ok: HeroSlide;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addHeroSlide(arg0, await to_candid_HeroSlide_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHeroSlide(arg0, await to_candid_HeroSlide_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteActivity(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteArea(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArea(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArea(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContactSubmission(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactSubmission(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactSubmission(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFooterLink(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFooterLink(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFooterLink(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteHeroSlide(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHeroSlide(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHeroSlide(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSubmission(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async emergencyResetPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.emergencyResetPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emergencyResetPassword(arg0);
            return result;
        }
    }
    async getAbout(): Promise<AboutContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getAbout();
                return from_candid_AboutContent_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAbout();
            return from_candid_AboutContent_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivities(arg0: Topic | null): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivities(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivities(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityBySlug(arg0: string): Promise<Activity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityBySlug(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityBySlug(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActivitiesAdmin(arg0: Topic | null): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivitiesAdmin(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivitiesAdmin(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHeroSlides(): Promise<Array<HeroSlide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHeroSlides();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHeroSlides();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAreas(): Promise<Array<Area>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAreas();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAreas();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBackgrounds(): Promise<Array<Background>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackgrounds();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackgrounds();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInfo(): Promise<ContactInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<ContactSubmission>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions(arg0);
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions(arg0);
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFooterLinks(): Promise<Array<FooterLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFooterLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFooterLinks();
            return result;
        }
    }
    async getHeroSlides(arg0: Topic): Promise<Array<HeroSlide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeroSlides(to_candid_Topic_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeroSlides(to_candid_Topic_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistrationSubmissions(arg0: bigint | null): Promise<Array<RegistrationSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationSubmissions(to_candid_opt_n54(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationSubmissions(to_candid_opt_n54(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteSettings(): Promise<SiteSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reorderAreas(arg0: string, arg1: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderAreas(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderAreas(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderFooterLinks(arg0: string, arg1: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderFooterLinks(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderFooterLinks(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderHeroSlides(arg0: string, arg1: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderHeroSlides(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderHeroSlides(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetAdminPassword(arg0: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdminPassword(arg0);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdminPassword(arg0);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedSampleData(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async setAbout(arg0: string, arg1: AboutContent): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAbout(arg0, to_candid_AboutContent_n63(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAbout(arg0, to_candid_AboutContent_n63(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setAreaBackground(arg0: string, arg1: bigint, arg2: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: Area | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAreaBackground(arg0, arg1, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAreaBackground(arg0, arg1, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAreaBackgroundVideo(arg0: string, arg1: bigint, arg2: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: Area | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAreaBackgroundVideo(arg0, arg1, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAreaBackgroundVideo(arg0, arg1, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAreaCardBackground(arg0: string, arg1: bigint, arg2: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: Area | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAreaCardBackground(arg0, arg1, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAreaCardBackground(arg0, arg1, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async setBackground(arg0: string, arg1: Background): Promise<{
        __kind__: "ok";
        ok: Background;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setBackground(arg0, await to_candid_Background_n67(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBackground(arg0, await to_candid_Background_n67(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async setContactInfo(arg0: string, arg1: ContactInfo): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setContactInfo(arg0, to_candid_ContactInfo_n72(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setContactInfo(arg0, to_candid_ContactInfo_n72(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async setSiteSettings(arg0: string, arg1: SiteSettings): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setSiteSettings(arg0, await to_candid_SiteSettings_n74(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSiteSettings(arg0, await to_candid_SiteSettings_n74(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: ContactSubmissionInput): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(to_candid_ContactSubmissionInput_n76(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ContactSubmission_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(to_candid_ContactSubmissionInput_n76(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ContactSubmission_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRegistration(arg0: RegistrationInput): Promise<RegistrationSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRegistration(to_candid_RegistrationInput_n78(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RegistrationSubmission_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRegistration(to_candid_RegistrationInput_n78(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RegistrationSubmission_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateActivity(arg0: string, arg1: Activity): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, await to_candid_Activity_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, await to_candid_Activity_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAdminPassword(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminPassword(arg0, arg1, arg2);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminPassword(arg0, arg1, arg2);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateArea(arg0: string, arg1: bigint, arg2: AreaInput): Promise<{
        __kind__: "ok";
        ok: Area | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArea(arg0, arg1, arg2);
                return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArea(arg0, arg1, arg2);
            return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFooterLink(arg0: string, arg1: FooterLink): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFooterLink(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFooterLink(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHeroSlide(arg0: string, arg1: HeroSlide): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeroSlide(arg0, await to_candid_HeroSlide_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeroSlide(arg0, await to_candid_HeroSlide_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSubmissionStatus(arg0: string, arg1: bigint, arg2: SubmissionStatus): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionStatus(arg0, arg1, to_candid_SubmissionStatus_n80(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionStatus(arg0, arg1, to_candid_SubmissionStatus_n80(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AboutContent_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AboutContent): AboutContent {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Activity_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Promise<Activity> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_Area_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Area): Promise<Area> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_BackgroundScope_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackgroundScope): BackgroundScope {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_Background_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Background): Promise<Background> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ContactInfo_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactInfo): ContactInfo {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ContactSubmission_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactSubmission): ContactSubmission {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HeroSlide_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeroSlide): Promise<HeroSlide> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationSubmission_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationSubmission): RegistrationSubmission {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
async function from_candid_SiteSettings_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteSettings): Promise<SiteSettings> {
    return await from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Topic_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Topic): Topic {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Activity]): Promise<Activity | null> {
    return value.length === 0 ? null : await from_candid_Activity_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactInfo]): ContactInfo | null {
    return value.length === 0 ? null : from_candid_ContactInfo_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SiteSettings]): Promise<SiteSettings | null> {
    return value.length === 0 ? null : await from_candid_SiteSettings_n61(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Area]): Promise<Area | null> {
    return value.length === 0 ? null : await from_candid_Area_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contentFa: string;
    contentSv: string;
    topic: _Topic;
    descriptionFa: string;
    descriptionSv: string;
    createdAt: bigint;
    slug: string;
    isActive: boolean;
    updatedAt: bigint;
    imageUrl: [] | [_ExternalBlob];
    hasRegistrationForm: boolean;
    titleFa: string;
    titleSv: string;
}): Promise<{
    id: bigint;
    contentFa: string;
    contentSv: string;
    topic: Topic;
    descriptionFa: string;
    descriptionSv: string;
    createdAt: bigint;
    slug: string;
    isActive: boolean;
    updatedAt: bigint;
    imageUrl?: ExternalBlob;
    hasRegistrationForm: boolean;
    titleFa: string;
    titleSv: string;
}> {
    return {
        id: value.id,
        contentFa: value.contentFa,
        contentSv: value.contentSv,
        topic: from_candid_Topic_n16(_uploadFile, _downloadFile, value.topic),
        descriptionFa: value.descriptionFa,
        descriptionSv: value.descriptionSv,
        createdAt: value.createdAt,
        slug: value.slug,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        imageUrl: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.imageUrl)),
        hasRegistrationForm: value.hasRegistrationForm,
        titleFa: value.titleFa,
        titleSv: value.titleSv
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    order: bigint;
    icon: string;
    cardBackground: [] | [_ExternalBlob];
    subtitleFa: string;
    subtitleSv: string;
    areaBackgroundVideo: [] | [_ExternalBlob];
    areaBackground: [] | [_ExternalBlob];
    titleFa: string;
    titleSv: string;
}): Promise<{
    id: bigint;
    order: bigint;
    icon: string;
    cardBackground?: ExternalBlob;
    subtitleFa: string;
    subtitleSv: string;
    areaBackgroundVideo?: ExternalBlob;
    areaBackground?: ExternalBlob;
    titleFa: string;
    titleSv: string;
}> {
    return {
        id: value.id,
        order: value.order,
        icon: value.icon,
        cardBackground: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.cardBackground)),
        subtitleFa: value.subtitleFa,
        subtitleSv: value.subtitleSv,
        areaBackgroundVideo: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.areaBackgroundVideo)),
        areaBackground: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.areaBackground)),
        titleFa: value.titleFa,
        titleSv: value.titleSv
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: _Topic;
    order: bigint;
    isActive: boolean;
    imageUrl: [] | [_ExternalBlob];
    subtitleFa: string;
    subtitleSv: string;
    titleFa: string;
    titleSv: string;
}): Promise<{
    id: bigint;
    topic: Topic;
    order: bigint;
    isActive: boolean;
    imageUrl?: ExternalBlob;
    subtitleFa: string;
    subtitleSv: string;
    titleFa: string;
    titleSv: string;
}> {
    return {
        id: value.id,
        topic: from_candid_Topic_n16(_uploadFile, _downloadFile, value.topic),
        order: value.order,
        isActive: value.isActive,
        imageUrl: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.imageUrl)),
        subtitleFa: value.subtitleFa,
        subtitleSv: value.subtitleSv,
        titleFa: value.titleFa,
        titleSv: value.titleSv
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contentFa: string;
    contentSv: string;
    imagePath: [] | [string];
}): {
    id: bigint;
    contentFa: string;
    contentSv: string;
    imagePath?: string;
} {
    return {
        id: value.id,
        contentFa: value.contentFa,
        contentSv: value.contentSv,
        imagePath: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.imagePath))
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    activitySlug: [] | [string];
    scope: _BackgroundScope;
    imageUrl: [] | [_ExternalBlob];
    mediaType: [] | [string];
}): Promise<{
    id: bigint;
    activitySlug?: string;
    scope: BackgroundScope;
    imageUrl?: ExternalBlob;
    mediaType?: string;
}> {
    return {
        id: value.id,
        activitySlug: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.activitySlug)),
        scope: from_candid_BackgroundScope_n43(_uploadFile, _downloadFile, value.scope),
        imageUrl: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.imageUrl)),
        mediaType: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.mediaType))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    email: string;
    addressFa: string;
    addressSv: string;
    mapEmbedUrl: [] | [string];
    phone: string;
}): {
    id: bigint;
    email: string;
    addressFa: string;
    addressSv: string;
    mapEmbedUrl?: string;
    phone: string;
} {
    return {
        id: value.id,
        email: value.email,
        addressFa: value.addressFa,
        addressSv: value.addressSv,
        mapEmbedUrl: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.mapEmbedUrl)),
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: [] | [string];
}): {
    id: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone?: string;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SubmissionStatus;
    nameFa: [] | [string];
    nameSv: [] | [string];
    activityId: bigint;
    submittedAt: bigint;
    email: string;
    message: [] | [string];
    phone: [] | [string];
}): {
    id: bigint;
    status: SubmissionStatus;
    nameFa?: string;
    nameSv?: string;
    activityId: bigint;
    submittedAt: bigint;
    email: string;
    message?: string;
    phone?: string;
} {
    return {
        id: value.id,
        status: from_candid_SubmissionStatus_n58(_uploadFile, _downloadFile, value.status),
        nameFa: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.nameFa)),
        nameSv: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.nameSv)),
        activityId: value.activityId,
        submittedAt: value.submittedAt,
        email: value.email,
        message: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.message)),
        phone: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.phone))
    };
}
async function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    landingSubtitleFa: string;
    landingSubtitleSv: string;
    primaryColor: string;
    topicsBgVideo: [] | [_ExternalBlob];
    accentColor: string;
    logoUrl: [] | [_ExternalBlob];
    adminPassword: string;
    secondaryColor: string;
    topicsBgImage: [] | [_ExternalBlob];
    titleFa: string;
    titleSv: string;
}): Promise<{
    id: bigint;
    landingSubtitleFa: string;
    landingSubtitleSv: string;
    primaryColor: string;
    topicsBgVideo?: ExternalBlob;
    accentColor: string;
    logoUrl?: ExternalBlob;
    adminPassword: string;
    secondaryColor: string;
    topicsBgImage?: ExternalBlob;
    titleFa: string;
    titleSv: string;
}> {
    return {
        id: value.id,
        landingSubtitleFa: value.landingSubtitleFa,
        landingSubtitleSv: value.landingSubtitleSv,
        primaryColor: value.primaryColor,
        topicsBgVideo: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.topicsBgVideo)),
        accentColor: value.accentColor,
        logoUrl: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.logoUrl)),
        adminPassword: value.adminPassword,
        secondaryColor: value.secondaryColor,
        topicsBgImage: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.topicsBgImage)),
        titleFa: value.titleFa,
        titleSv: value.titleSv
    };
}
async function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Activity;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: Activity;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_Activity_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Sport: null;
} | {
    Cultural: null;
} | {
    Educational: null;
}): Topic {
    return "Sport" in value ? Topic.Sport : "Cultural" in value ? Topic.Cultural : "Educational" in value ? Topic.Educational : value;
}
async function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Area;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: Area;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_Area_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FooterLink;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FooterLink;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HeroSlide;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: HeroSlide;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_HeroSlide_n27(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Sport: null;
} | {
    Cultural: null;
} | {
    Educational: null;
} | {
    Landing: null;
} | {
    Activity: null;
}): BackgroundScope {
    return "Sport" in value ? BackgroundScope.Sport : "Cultural" in value ? BackgroundScope.Cultural : "Educational" in value ? BackgroundScope.Educational : "Landing" in value ? BackgroundScope.Landing : "Activity" in value ? BackgroundScope.Activity : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ContactSubmission>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<ContactSubmission>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n51(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): SubmissionStatus {
    return "Approved" in value ? SubmissionStatus.Approved : "Rejected" in value ? SubmissionStatus.Rejected : "Pending" in value ? SubmissionStatus.Pending : value;
}
async function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_Area];
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: Area | null;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_opt_n66(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Background;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: Background;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_Background_n41(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Promise<Array<Activity>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Activity_n14(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HeroSlide>): Promise<Array<HeroSlide>> {
    return await Promise.all(value.map(async (x)=>await from_candid_HeroSlide_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Area>): Promise<Array<Area>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Area_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Background>): Promise<Array<Background>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Background_n41(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactSubmission>): Array<ContactSubmission> {
    return value.map((x)=>from_candid_ContactSubmission_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegistrationSubmission>): Array<RegistrationSubmission> {
    return value.map((x)=>from_candid_RegistrationSubmission_n56(_uploadFile, _downloadFile, x));
}
function to_candid_AboutContent_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AboutContent): _AboutContent {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
async function to_candid_Activity_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Activity): Promise<_Activity> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_BackgroundScope_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundScope): _BackgroundScope {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
async function to_candid_Background_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Background): Promise<_Background> {
    return await to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_ContactInfo_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactInfo): _ContactInfo {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_ContactSubmissionInput_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactSubmissionInput): _ContactSubmissionInput {
    return to_candid_record_n77(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_HeroSlide_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeroSlide): Promise<_HeroSlide> {
    return await to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationInput_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationInput): _RegistrationInput {
    return to_candid_record_n79(_uploadFile, _downloadFile, value);
}
async function to_candid_SiteSettings_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteSettings): Promise<_SiteSettings> {
    return await to_candid_record_n75(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionStatus_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): _SubmissionStatus {
    return to_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function to_candid_Topic_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Topic): _Topic {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Topic | null): [] | [_Topic] {
    return value === null ? candid_none() : candid_some(to_candid_Topic_n10(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: Topic;
    order: bigint;
    isActive: boolean;
    imageUrl?: ExternalBlob;
    subtitleFa: string;
    subtitleSv: string;
    titleFa: string;
    titleSv: string;
}): Promise<{
    id: bigint;
    topic: _Topic;
    order: bigint;
    isActive: boolean;
    imageUrl: [] | [_ExternalBlob];
    subtitleFa: string;
    subtitleSv: string;
    titleFa: string;
    titleSv: string;
}> {
    return {
        id: value.id,
        topic: to_candid_Topic_n10(_uploadFile, _downloadFile, value.topic),
        order: value.order,
        isActive: value.isActive,
        imageUrl: value.imageUrl ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.imageUrl)) : candid_none(),
        subtitleFa: value.subtitleFa,
        subtitleSv: value.subtitleSv,
        titleFa: value.titleFa,
        titleSv: value.titleSv
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contentFa: string;
    contentSv: string;
    imagePath?: string;
}): {
    id: bigint;
    contentFa: string;
    contentSv: string;
    imagePath: [] | [string];
} {
    return {
        id: value.id,
        contentFa: value.contentFa,
        contentSv: value.contentSv,
        imagePath: value.imagePath ? candid_some(value.imagePath) : candid_none()
    };
}
async function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    activitySlug?: string;
    scope: BackgroundScope;
    imageUrl?: ExternalBlob;
    mediaType?: string;
}): Promise<{
    id: bigint;
    activitySlug: [] | [string];
    scope: _BackgroundScope;
    imageUrl: [] | [_ExternalBlob];
    mediaType: [] | [string];
}> {
    return {
        id: value.id,
        activitySlug: value.activitySlug ? candid_some(value.activitySlug) : candid_none(),
        scope: to_candid_BackgroundScope_n69(_uploadFile, _downloadFile, value.scope),
        imageUrl: value.imageUrl ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.imageUrl)) : candid_none(),
        mediaType: value.mediaType ? candid_some(value.mediaType) : candid_none()
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    email: string;
    addressFa: string;
    addressSv: string;
    mapEmbedUrl?: string;
    phone: string;
}): {
    id: bigint;
    email: string;
    addressFa: string;
    addressSv: string;
    mapEmbedUrl: [] | [string];
    phone: string;
} {
    return {
        id: value.id,
        email: value.email,
        addressFa: value.addressFa,
        addressSv: value.addressSv,
        mapEmbedUrl: value.mapEmbedUrl ? candid_some(value.mapEmbedUrl) : candid_none(),
        phone: value.phone
    };
}
async function to_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    landingSubtitleFa: string;
    landingSubtitleSv: string;
    primaryColor: string;
    topicsBgVideo?: ExternalBlob;
    accentColor: string;
    logoUrl?: ExternalBlob;
    adminPassword: string;
    secondaryColor: string;
    topicsBgImage?: ExternalBlob;
    titleFa: string;
    titleSv: string;
}): Promise<{
    id: bigint;
    landingSubtitleFa: string;
    landingSubtitleSv: string;
    primaryColor: string;
    topicsBgVideo: [] | [_ExternalBlob];
    accentColor: string;
    logoUrl: [] | [_ExternalBlob];
    adminPassword: string;
    secondaryColor: string;
    topicsBgImage: [] | [_ExternalBlob];
    titleFa: string;
    titleSv: string;
}> {
    return {
        id: value.id,
        landingSubtitleFa: value.landingSubtitleFa,
        landingSubtitleSv: value.landingSubtitleSv,
        primaryColor: value.primaryColor,
        topicsBgVideo: value.topicsBgVideo ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.topicsBgVideo)) : candid_none(),
        accentColor: value.accentColor,
        logoUrl: value.logoUrl ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.logoUrl)) : candid_none(),
        adminPassword: value.adminPassword,
        secondaryColor: value.secondaryColor,
        topicsBgImage: value.topicsBgImage ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.topicsBgImage)) : candid_none(),
        titleFa: value.titleFa,
        titleSv: value.titleSv
    };
}
function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    message: string;
    phone?: string;
}): {
    name: string;
    email: string;
    message: string;
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email,
        message: value.message,
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nameFa?: string;
    nameSv?: string;
    activityId: bigint;
    email: string;
    message?: string;
    phone?: string;
}): {
    nameFa: [] | [string];
    nameSv: [] | [string];
    activityId: bigint;
    email: string;
    message: [] | [string];
    phone: [] | [string];
} {
    return {
        nameFa: value.nameFa ? candid_some(value.nameFa) : candid_none(),
        nameSv: value.nameSv ? candid_some(value.nameSv) : candid_none(),
        activityId: value.activityId,
        email: value.email,
        message: value.message ? candid_some(value.message) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contentFa: string;
    contentSv: string;
    topic: Topic;
    descriptionFa: string;
    descriptionSv: string;
    createdAt: bigint;
    slug: string;
    isActive: boolean;
    updatedAt: bigint;
    imageUrl?: ExternalBlob;
    hasRegistrationForm: boolean;
    titleFa: string;
    titleSv: string;
}): Promise<{
    id: bigint;
    contentFa: string;
    contentSv: string;
    topic: _Topic;
    descriptionFa: string;
    descriptionSv: string;
    createdAt: bigint;
    slug: string;
    isActive: boolean;
    updatedAt: bigint;
    imageUrl: [] | [_ExternalBlob];
    hasRegistrationForm: boolean;
    titleFa: string;
    titleSv: string;
}> {
    return {
        id: value.id,
        contentFa: value.contentFa,
        contentSv: value.contentSv,
        topic: to_candid_Topic_n10(_uploadFile, _downloadFile, value.topic),
        descriptionFa: value.descriptionFa,
        descriptionSv: value.descriptionSv,
        createdAt: value.createdAt,
        slug: value.slug,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        imageUrl: value.imageUrl ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.imageUrl)) : candid_none(),
        hasRegistrationForm: value.hasRegistrationForm,
        titleFa: value.titleFa,
        titleSv: value.titleSv
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Topic): {
    Sport: null;
} | {
    Cultural: null;
} | {
    Educational: null;
} {
    return value == Topic.Sport ? {
        Sport: null
    } : value == Topic.Cultural ? {
        Cultural: null
    } : value == Topic.Educational ? {
        Educational: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundScope): {
    Sport: null;
} | {
    Cultural: null;
} | {
    Educational: null;
} | {
    Landing: null;
} | {
    Activity: null;
} {
    return value == BackgroundScope.Sport ? {
        Sport: null
    } : value == BackgroundScope.Cultural ? {
        Cultural: null
    } : value == BackgroundScope.Educational ? {
        Educational: null
    } : value == BackgroundScope.Landing ? {
        Landing: null
    } : value == BackgroundScope.Activity ? {
        Activity: null
    } : value;
}
function to_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
} {
    return value == SubmissionStatus.Approved ? {
        Approved: null
    } : value == SubmissionStatus.Rejected ? {
        Rejected: null
    } : value == SubmissionStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}

export const canisterIds: Record<string, string> | undefined = { backend: process.env.CANISTER_ID_BACKEND };
